@Library("shared-jenkins-library@latest") _

def buildType = isBranchType('release') ? 'release' : 'debug'
def publishable = isBranch('master') || isBranchType('release')

runPipeline(
    nodeLabel: 'TO-MAC-12',
    parameters: [
        choice(name: 'ENVIRONMENT', choices: ['debug','prodc', 'proda']),
    ]
) { cts ->
    stage('SetupNode') {
        sh '''
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install 14.17.5 || nvm use 14.17.5
        npm -v
        '''
    }

    stage('Build') {
        sh "./.cicd/scripts/build.sh"
    }

    stage('Archive') {
        archiveArtifacts artifacts: '**/build/*.zip', allowEmptyArchive: true
    }
}
