@Library("shared-jenkins-library@latest") _

def buildType = isBranchType('release') ? 'release' : 'debug'
def publishable = isBranch('master') || isBranchType('release')

runPipeline(
    nodeLabel: 'TO-MAC-12',
    parameters: [
        choice(name: 'ENVIRONMENT', choices: ['debug','prodc', 'proda']),
    ]
) { cts ->
    stage('SetupNode'){
        sh 'bash -l -c ". $HOME/.nvm/nvm.sh ; nvm use 14.17.5 || nvm install 14.17.5 && nvm use 14.17.5 ; npm -v "'
    }

    stage('Build') {
        withEnv(["NVM_DIR=$HOME/.nvm"]) {
        sh '''
        . $NVM_DIR/nvm.sh
        nvm use 14.17.5
        npm -v
        ./cicd/scripts/build.sh
        '''
    }
    }

    stage('Archive') {
        steps {
            archiveArtifacts artifacts: '**/build/*.zip', allowEmptyArchive: true
        }
    }
}